CREATE TABLE BillOfLading (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Numero NVARCHAR(50) NOT NULL,
    Consignee NVARCHAR(100) NOT NULL,
    Navio NVARCHAR(100) NOT NULL
);

CREATE TABLE Container (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Numero CHAR(11) NOT NULL,
    Tamanho INT NOT NULL,
    Tipo NVARCHAR(50) NOT NULL,
    BillOfLadingID INT,
    FOREIGN KEY (BillOfLadingID) REFERENCES BillOfLading(ID) ON DELETE CASCADE
);
